---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: redis
  labels:
    app: redis
data:
  redis-config: |
    maxmemory 100mb
    maxmemory-policy allkeys-lru
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          command:
            - redis-server
            - "/redis-config/redis.conf"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "0.1"
              memory: "512Mi"
          volumeMounts:
          - mountPath: /redis-config
            name: conf
      volumes:
      - name: conf
        configMap:
          name: redis-configmap
          items:
            - key: redis-config
              path: redis.conf
---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
